# Generated by Django 5.2.3 on 2025-07-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionlock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='morse_pin',
            field=models.CharField(max_length=255),
        ),
    ]
