# Generated by Django 5.2.3 on 2025-07-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visionlock_app', '0002_alter_userprofile_morse_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='sachinpawar.ka@gmail.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='face_encoding',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='morse_pin',
            field=models.CharField(max_length=256),
        ),
    ]
